### ISSUE TITLE
您好，模板可否能自行修改

### ISSUE THREAD

**Issue by Z471994** [freddyy2024/FrameXT#1]
通用白色边框或底部边框在去掉拍摄时间这一栏后，会出现空白段，可否自定义这部分格式
<img width="1362" alt="截屏2024-11-29 00 48 14" src="https://github.com/user-attachments/assets/3462569c-f905-4051-90bc-bd4c18b89173">

**Comment by freddyy2024** [comment]
> 通用白色边框或底部边框在去掉拍摄时间这一栏后，会出现空白段，可否自定义这部分格式 <img alt="截屏2024-11-29 00 48 14" width="1362" src="https://private-user-images.githubusercontent.com/71478353/390861205-3462569c-f905-4051-90bc-bd4c18b89173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMTcxNTAsIm5iZiI6MTczMzExNjg1MCwicGF0aCI6Ii83MTQ3ODM1My8zOTA4NjEyMDUtMzQ2MjU2OWMtZjkwNS00MDUxLTkwYmMtYmQ0YzE4Yjg5MTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA1MjA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MWFmMWM0NGJkOWVmNDdhYjk0YWIwZDkwZDI3MDI2OTdmNTZiNjdhYmEwMzY1Yjc2MjkyMjgyYjc2YTg5NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f4rq96LN4qrM5gH95quHZxKknl47UOoJVoY4kxxXfa0">

目前还不支持，计划在下个版本更新支持定制调整。

**Comment by Z471994** [comment]
非常感谢

**Comment by freddyy2024** [comment]
已经更新版本V1.0.1,可以下载最新版。
![微信截图_20241208234234](https://github.com/user-attachments/assets/89078609-fbbb-4c70-83f3-fe076572aa08)

**Comment by Z471994** [comment]
您好，Mac版压缩包更新为1.0.1，但是内部文件还是1.0.0，请您替换上传
![Uploading 截屏2024-12-10 22.51.11.png…]()

**Comment by freddyy2024** [comment]
已经更新了 1.0.2 版本，可以先卸载原来的软件，重新安装试试。
